import * as React from "react";
import { Image, Pressable, ScrollView, StyleSheet, View } from "react-native";
import { AppCard, AppScreen, AppSection, MenuRow, MetricGrid } from "@/components/app";
import { Button, Icon, Text } from "@/components/primitives";
import { getCachedClientDashboardData, getCachedCurrentClientOwnerProfileForApp, getCurrentClientDashboardData, getCurrentClientOwnerProfileForApp } from "@/services/client-data";
import { runGingrDiscovery } from "@/services/gingr";
import type { GingrDiscoveryAction } from "@/services/gingr";
import { colors, fonts, radii, spacing, typography } from "@/theme";
import { useSession } from "@/utils/session";

const debugActions: Array<{ action: GingrDiscoveryAction; label: string }> = [
  { action: "current-owner-profile", label: "Test Owner Profile" }, { action: "current-pets", label: "Test Current Pets" },
  { action: "current-reservations", label: "Test Reservations" }, { action: "reservation-detail-test", label: "Test Reservation Detail" },
  { action: "estimate-test", label: "Test Estimate" }, { action: "list-invoices", label: "Test Invoices" },
  { action: "current-client-snapshot", label: "Test Snapshot" },
];
export function AccountRedesignScreen() {
  const { client, user } = useSession(); const cached = getCachedClientDashboardData();
  const [profile, setProfile] = React.useState<Awaited<ReturnType<typeof getCurrentClientOwnerProfileForApp>>>(getCachedCurrentClientOwnerProfileForApp() ?? null);
  const [counts, setCounts] = React.useState({ pets: cached?.pets.length ?? 0, reservations: (cached?.pastReservations.length ?? 0) + (cached?.upcomingReservations.length ?? 0) });
  const [showDebug, setShowDebug] = React.useState(false); const [debugLoading, setDebugLoading] = React.useState(false); const [debugOutput, setDebugOutput] = React.useState<string | null>(null);
  React.useEffect(() => { void Promise.all([getCurrentClientOwnerProfileForApp(), getCurrentClientDashboardData()]).then(([owner, data]) => { setProfile(owner); setCounts({ pets: data.pets.length, reservations: data.pastReservations.length + data.upcomingReservations.length }); }); }, []);
  async function runDebug(action: GingrDiscoveryAction) { setDebugLoading(true); setDebugOutput(null); try { setDebugOutput(JSON.stringify(await runGingrDiscovery({ action }), null, 2)); } catch (error) { setDebugOutput(error instanceof Error ? error.message : "Gingr request failed."); } finally { setDebugLoading(false); } }
  const name = client?.display_name ?? profile?.displayName ?? "Le Chateau Guest"; const email = client?.email ?? user?.email ?? ""; const phone = readOwnerPhone(profile?.rawOwner);
  return <AppScreen title="Account" subtitle="Manage your profile and preferences.">
    <Pressable><AppCard style={styles.profileCard}>{profile?.imageUrl ? <Image source={{ uri: profile.imageUrl }} style={styles.profileImage} /> : <View style={styles.profilePlaceholder}><Text style={styles.initials}>{getInitials(name)}</Text></View>}<View style={styles.profileCopy}><Text style={typography.heroName}>{name}</Text><Text style={typography.bodySecondary}>{email}</Text><Text style={typography.bodySecondary}>{phone}</Text><View style={styles.badges}><View style={styles.verified}><Text style={styles.badgeText}>Verified</Text><Icon color={colors.goldDark} name="check" size={13} /></View><View style={styles.primary}><Text style={styles.badgeText}>Primary Contact</Text></View></View></View><Icon color={colors.icon} name="chevron-right" size={24} /></AppCard></Pressable>
    <AppSection title="Account Overview"><MetricGrid items={[{ icon: "calendar", label: "Reservations", value: String(counts.reservations), action: "View all" }, { icon: "paw", label: "Pets", value: String(counts.pets), action: "View all" }, { icon: "file", label: "Payments", value: "—", action: "View history" }, { icon: "camera", label: "Webcams", value: "3", action: "View all" }]} /></AppSection>
    <AppSection title="Account Settings"><AppCard padding="none" variant="flushRows"><MenuRow icon="user" title="Personal Information" subtitle="Update your name, email, phone and address" /><MenuRow icon="lock" title="Login & Security" subtitle="Manage your password and security settings" /><MenuRow icon="bell" title="Notification Preferences" subtitle="Choose how you want to be notified" /><MenuRow icon="credit-card" title="Payment Methods" subtitle="Manage your saved payment methods" /><MenuRow icon="file" title="Policies & Agreements" subtitle="View and manage your agreements" isLast /></AppCard></AppSection>
    <AppSection title="Preferences"><AppCard padding="none" variant="flushRows"><MenuRow icon="paw" title="Pet Care Preferences" subtitle="Feeding, playtime, and care instructions" /><MenuRow icon="calendar" title="Reservation Preferences" subtitle="Your check-in, pickup and stay preferences" /><MenuRow icon="heart" title="Communication Preferences" subtitle="How we communicate with you" isLast /></AppCard></AppSection>
    <Text style={styles.memberSince}>Member since {formatMemberSince(client?.created_at)}</Text>
    <Pressable onPress={() => setShowDebug((value) => !value)} style={styles.debugToggle}><Text style={typography.cardTitle}>Gingr Debug</Text><Icon color={colors.icon} name={showDebug ? "chevron-up" : "chevron-down"} size={20} /></Pressable>
    {showDebug ? <AppCard style={styles.debugCard}><View style={styles.debugButtons}>{debugActions.map((item) => <Button key={item.action} disabled={debugLoading} onPress={() => void runDebug(item.action)} title={item.label} variant="secondary" style={styles.debugButton} />)}</View>{debugLoading ? <Text>Calling Gingr…</Text> : null}{debugOutput ? <ScrollView nestedScrollEnabled style={styles.debugOutput}><Text selectable style={styles.debugText}>{debugOutput}</Text></ScrollView> : null}</AppCard> : null}
  </AppScreen>;
}
function readOwnerPhone(owner?: Record<string, unknown>) { if (!owner) return "Phone not listed"; for (const key of ["cell_phone","phone","home_phone","mobile_phone"]) { const value = owner[key]; if (typeof value === "string" && value.trim()) return value.trim(); } return "Phone not listed"; }
function getInitials(name: string) { return name.split(/\s+/).slice(0,2).map((part) => part[0]?.toUpperCase()).join(""); }
function formatMemberSince(value?: string) { if (!value) return "your first visit"; const date = new Date(value); return Number.isNaN(date.getTime()) ? value : date.toLocaleDateString(undefined,{month:"long",day:"numeric",year:"numeric"}); }
const styles = StyleSheet.create({ profileCard: { alignItems: "center", flexDirection: "row", gap: spacing[18] }, profileImage: { borderRadius: radii.circle, height: 118, width: 118 }, profilePlaceholder: { alignItems: "center", backgroundColor: colors.goldSoft, borderRadius: radii.circle, height: 118, justifyContent: "center", width: 118 }, initials: { color: colors.burgundy, fontFamily: fonts.display, fontSize: 32 }, profileCopy: { flex: 1, gap: spacing[6] }, badges: { flexDirection: "row", flexWrap: "wrap", gap: spacing[8], marginTop: spacing[6] }, verified: { alignItems: "center", backgroundColor: colors.goldSoft, borderRadius: 8, flexDirection: "row", gap: 5, paddingHorizontal: 11, paddingVertical: 7 }, primary: { backgroundColor: colors.burgundySoft, borderRadius: 8, paddingHorizontal: 11, paddingVertical: 7 }, badgeText: { fontSize: 12 }, memberSince: { color: colors.textSecondary, textAlign: "center" }, debugToggle: { alignItems: "center", borderTopColor: colors.divider, borderTopWidth: 1, flexDirection: "row", justifyContent: "space-between", minHeight: 52 }, debugCard: { gap: spacing[12] }, debugButtons: { flexDirection: "row", flexWrap: "wrap", gap: spacing[8] }, debugButton: { flexGrow: 1, minHeight: 44 }, debugOutput: { backgroundColor: colors.surfaceMuted, borderRadius: 8, maxHeight: 320, padding: spacing[10] }, debugText: { fontFamily: "Courier", fontSize: 10, lineHeight: 14 } });
