import { router, useFocusEffect } from "expo-router";
import * as React from "react";
import { Image, Pressable, ScrollView, StyleSheet, View } from "react-native";
import { AppCard, AppScreen, AppSection } from "@/components/app";
import { Icon, Text } from "@/components/primitives";
import { resortImages } from "@/data/mock-data";
import { getCachedClientDashboardData, getCurrentClientDashboardData } from "@/services/client-data";
import { colors, fonts, radii, spacing, typography } from "@/theme";
import type { ClientReservation, Pet } from "@/types/app";
import { useSession } from "@/utils/session";
import { getVaccinationStatus } from "@/utils/vaccinations";

type State = { pets: Pet[]; upcomingReservations: ClientReservation[] };
const quickActions = [
  { icon: "file", label: "Upload Vaccinations", onPress: () => router.push("/document-upload") },
  { icon: "camera", label: "View Webcams", onPress: () => router.push("/live-cameras") },
  { icon: "calendar", label: "View Reservations", onPress: () => router.push("/reservations") },
] as const;

export function HomeRedesignScreen() {
  const { client } = useSession(); const cached = getCachedClientDashboardData();
  const [state, setState] = React.useState<State>({ pets: cached?.pets ?? [], upcomingReservations: cached?.upcomingReservations ?? [] });
  const load = React.useCallback(() => { void getCurrentClientDashboardData().then((data) => setState({ pets: data.pets, upcomingReservations: data.upcomingReservations })); }, []);
  useFocusEffect(load); const reservation = state.upcomingReservations[0]; const pet = state.pets.find((item) => reservation?.petNames.includes(item.name)) ?? state.pets[0];
  const firstName = client?.display_name?.trim().split(/\s+/)[0] || "Guest";
  return <AppScreen>
    <View style={styles.welcome}><View style={styles.welcomeCopy}><Text numberOfLines={1} style={styles.welcomeTitle}>Welcome, {firstName}!</Text><Text style={typography.bodySecondary}>Here’s what’s happening with your pets.</Text></View><Pressable onPress={() => router.push("/request-reservation")} style={styles.newReservation}><Icon color={colors.burgundy} name="calendar" size={21} /><Text numberOfLines={1} style={styles.newReservationText}>New Reservation</Text></Pressable></View>
    {reservation ? <Pressable onPress={() => router.push({ pathname: "/reservation-detail", params: { reservationIds: reservation.id } })}><AppCard style={styles.reservationCard}><View style={styles.eyebrow}><Icon color={colors.icon} name="calendar" size={21} /><Text style={styles.eyebrowText}>UPCOMING RESERVATION</Text></View><View style={styles.reservationMain}>{pet ? <Image source={{ uri: pet.imageUrl }} style={styles.reservationImage} /> : null}<View style={styles.reservationCopy}><Text style={typography.heroName}>{pet?.name ?? reservation.petNames.join(", ")}</Text><Text style={typography.body}>{reservation.dateRange}</Text><Text style={typography.bodySecondary}>{reservation.reservationType || "Reservation"}</Text><View style={[styles.confirmed,isConfirmedReservationStatus(reservation.status)&&confirmedStatusStyles.pill]}><Text style={[styles.confirmedText,isConfirmedReservationStatus(reservation.status)&&confirmedStatusStyles.text]}>{reservation.status.toUpperCase()}</Text></View></View><Icon color={colors.icon} name="chevron-right" size={24} /></View><View style={styles.stayFacts}><Fact label="CHECK-IN" value={formatDate(reservation.startDate)} subvalue={formatTimeOnly(reservation.checkInAt??reservation.startDateTimeLabel)} /><Fact bordered label="CHECK-OUT" value={formatDate(reservation.endDate)} subvalue={formatTimeOnly(reservation.checkOutAt??reservation.endDateTimeLabel)} /><Fact label="TOTAL STAY" value={formatNights(reservation.startDate, reservation.endDate)} /></View></AppCard></Pressable> : <AppCard><Text style={typography.cardTitle}>No upcoming reservations</Text><Text style={typography.bodySecondary}>When your next stay is confirmed, it will appear here.</Text></AppCard>}
    <AppSection title="Quick Actions"><View style={[styles.quickRow,quickActionLayoutStyles.row]}>{quickActions.map((action) => <Pressable key={action.label} onPress={action.onPress} style={[styles.quickCard,quickActionLayoutStyles.card]}><Icon color={colors.burgundy} name={action.icon} size={31} /><Text style={styles.quickLabel}>{action.label}</Text></Pressable>)}</View></AppSection>
    <AppSection actionLabel="View All" onAction={() => router.push("/pets")} title="Your Pets"><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.petRow}>{state.pets.map((item) => <Pressable key={item.id} onPress={() => router.push({ pathname: "/pet-profile", params: { petId: item.id } })} style={styles.petCard}><View><Image source={{ uri: item.imageUrl }} style={styles.petImage} /><VaccinationBadge pet={item} /></View><Text style={styles.petName}>{item.name}</Text><Text numberOfLines={1} style={styles.petMeta}>{item.breed}</Text><Text style={styles.petMeta}>{[item.age, item.gender].filter(Boolean).join(" · ")}</Text></Pressable>)}</ScrollView></AppSection>
    <AppSection title="Resort Updates"><AppCard style={styles.updateCard}><Image source={{ uri: resortImages.playYard }} style={styles.updateImage} /><View style={styles.updateCopy}><Text style={styles.updateLabel}>POOL SEASON IS HERE!</Text><Text style={typography.bodySecondary}>Our pools are open and ready for fun! Add Pool Time to your pet’s stay.</Text></View><Icon color={colors.burgundy} name="chevron-right" size={23} /></AppCard></AppSection>
  </AppScreen>;
}
function Fact({ bordered, label, subvalue, value }: { bordered?: boolean; label: string; subvalue?: string | null; value: string }) { return <View style={[styles.fact, denseFactStyles.fact, bordered && styles.factBorder]}><Text style={[styles.factLabel,denseFactStyles.label]}>{label}</Text><Text style={[styles.factValue,denseFactStyles.value]}>{value}</Text>{subvalue?<Text style={[styles.factSubvalue,denseFactStyles.subvalue]}>{subvalue}</Text>:null}</View>; }
const denseFactStyles=StyleSheet.create({fact:{gap:1},label:{lineHeight:14},value:{lineHeight:16},subvalue:{lineHeight:14}});
const quickActionLayoutStyles=StyleSheet.create({row:{flexDirection:"row"},card:{flex:1,minWidth:0,width:"auto"}});
const confirmedStatusStyles=StyleSheet.create({pill:{backgroundColor:colors.successSoft},text:{color:colors.success}});
function VaccinationBadge({ pet }: { pet: Pet }) { const status=getVaccinationStatus(pet);const color=status==="not_required"?colors.textSecondary:status==="current"?colors.success:status==="expired"?colors.error:colors.warning;const icon=status==="current"||status==="not_required"?"check":status==="expired"?"x":"info";const label=status==="not_required"?"Vaccinations not required":status==="current"?"Vaccinations up to date":status==="expired"?"Vaccinations expired":"Vaccination records needed";return <View accessibilityLabel={label} style={[styles.petCheck,{backgroundColor:color}]}><Icon color={colors.textInverse} name={icon} size={12}/></View>; }
function formatDate(value: string | null) { if (!value) return "Pending"; const [y,m,d] = value.split("-").map(Number); return new Date(y,m-1,d).toLocaleDateString(undefined,{month:"short",day:"numeric",year:"numeric"}); }
function isConfirmedReservationStatus(status:string){return status.trim().toLowerCase()==="confirmed";}
function formatTimeOnly(value: string | null) { if (!value) return null; const match=value.match(/\b(\d{1,2})(?::(\d{2}))?\s*([AP]M)\b/i); if(match){const [,hour,minutes,meridiem]=match;return`${hour}:${minutes??"00"} ${meridiem.toUpperCase()}`;} if(/T\d{2}:\d{2}/.test(value)){const date=new Date(value);if(!Number.isNaN(date.getTime()))return date.toLocaleTimeString(undefined,{hour:"numeric",minute:"2-digit"});} return null; }
function formatNights(start: string | null, end: string | null) { if (!start || !end) return "Pending"; const nights = Math.max(0, Math.round((new Date(end).getTime()-new Date(start).getTime())/86400000)); return `${nights} Night${nights===1?"":"s"}`; }
const styles = StyleSheet.create({ welcome: { alignItems: "center", flexDirection: "row", gap: spacing[12], justifyContent: "space-between" }, welcomeCopy: { flex: 1, gap: spacing[6], minWidth: 0 }, welcomeTitle: { color: colors.burgundy, fontFamily: fonts.display, fontSize: 27, lineHeight: 33 }, newReservation: { alignItems: "center", borderColor: colors.burgundy, borderRadius: 10, borderWidth: 1.25, flexDirection: "row", gap: spacing[6], justifyContent: "center", minHeight: 46, width: 140 }, newReservationText: { color: colors.burgundy, fontFamily: fonts.bodySemiBold, fontSize: 11 }, reservationCard: { gap: spacing[14] }, eyebrow: { alignItems: "center", flexDirection: "row", gap: spacing[10] }, eyebrowText: { color: colors.textSecondary, fontFamily: fonts.bodyMedium, fontSize: 13 }, reservationMain: { alignItems: "center", flexDirection: "row", gap: spacing[14] }, reservationImage: { borderRadius: radii.circle, height: 86, width: 86 }, reservationCopy: { flex: 1, gap: spacing[4] }, confirmed: { alignSelf: "flex-start", backgroundColor: colors.goldSoft, borderRadius: 8, marginTop: spacing[6], paddingHorizontal: spacing[12], paddingVertical: spacing[6] }, confirmedText: { color: colors.burgundy, fontFamily: fonts.bodySemiBold, fontSize: 12 }, stayFacts: { borderTopColor: colors.divider, borderTopWidth: 1, flexDirection: "row", paddingTop: spacing[12] }, fact: { alignItems: "center", flex: 1, gap: 4 }, factBorder: { borderColor: colors.divider, borderLeftWidth: 1, borderRightWidth: 1 }, factLabel: { color: colors.textSecondary, fontSize: 11 }, factValue: { color: colors.burgundy, fontFamily: fonts.bodyMedium, fontSize: 12, textAlign: "center" }, factSubvalue: { color: colors.textSecondary, fontSize: 10, textAlign: "center" }, quickRow: { gap: spacing[10] }, quickCard: { alignItems: "center", backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radii.card, borderWidth: 1, gap: spacing[14], height: 132, justifyContent: "center", padding: spacing[12], width: 118 }, quickLabel: { fontSize: 13, textAlign: "center" }, petRow: { gap: spacing[10] }, petCard: { alignItems: "center", backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radii.card, borderWidth: 1, gap: 4, padding: spacing[12], width: 150 }, petImage: { borderRadius: radii.circle, height: 90, width: 90 }, petCheck: { alignItems: "center", backgroundColor: colors.success, borderRadius: 11, height: 22, justifyContent: "center", position: "absolute", right: -2, top: -2, width: 22 }, petName: { color: colors.burgundy, fontFamily: fonts.display, fontSize: 19 }, petMeta: { color: colors.textSecondary, fontSize: 11, textAlign: "center" }, updateCard: { alignItems: "center", flexDirection: "row", gap: spacing[14] }, updateImage: { borderRadius: 10, height: 78, width: 118 }, updateCopy: { flex: 1, gap: spacing[6] }, updateLabel: { color: colors.goldDark, fontFamily: fonts.bodyMedium, fontSize: 13 } });
